<?php

namespace ContainerN80aQ50;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddAdminCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\AddAdminCommand' shared autowired service.
     *
     * @return \App\Command\AddAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'AddAdminCommand.php';

        $container->privates['App\\Command\\AddAdminCommand'] = $instance = new \App\Command\AddAdminCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->privates['App\\Repository\\Backend\\AdminRepository'] ?? $container->load('getAdminRepositoryService')));

        $instance->setName('app:add-admin');
        $instance->setDescription('Create Admin');

        return $instance;
    }
}
