<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPErx9m\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPErx9m/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXPErx9m.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXPErx9m\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXPErx9m\App_KernelDevDebugContainer([
    'container.build_hash' => 'XPErx9m',
    'container.build_id' => 'c648734c',
    'container.build_time' => 1650243495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPErx9m');
